#!/bin/bash

if [ $# -ge 3 ]; then
   echo "Too many arguments!!" >&2
   exit -1
fi

if [ $# -eq 0 ]; then
   echo "0 params"
   exit	-1
fi

if [ $1 == "-m" ]; then
	echo "ano"
elif [ $1 == "-d" ]; then
	echo `date`
fi
